### ISSUE TITLE
tat Clone Relics: The Great Hunter

### ISSUE THREAD

**Issue by ladybogit** [SWG-Source/dsrc#175] opened 2020-11-18 09:42 UTC
part 3 
1. duse not appear in journal  
2. when picking up terminal missions cancels the mission 

part 5
unable to hand in the convocation working just no quest update

**Comment by Cekis** [comment] 2022-09-23 07:23
I could not repeat this issue.  Part 3 shows up in the journal and I took a mission from the mission terminal after getting part 3 and it did not cancel.  Closing as not able to reproduce.

**Closed by Cekis** 2022-09-23 07:23 UTC
Labels: Bug
