### ISSUE TITLE
some npcs and ships models in game are replaced by some yellow/black/red cubes. how to fix that? in some space quests i was attacked by that yellow/black/red cubes instead of normal ship models. 

### ISSUE THREAD

**Issue by LORDANDERSON** [SWG-Source/dsrc#73] opened 2019-12-02 05:39 UTC
some npcs and ships models in game are replaced by some yellow/black/red cubes. how to fix that? in some space quests i was attacked by that yellow/black/red cubes instead of normal ship models.

**Comment by Cekis** [comment] 2019-12-02 06:23
Provide a screenshot please.  I don't think anybody else has seen this issue.

**Comment by LORDANDERSON** [comment] 2019-12-02 07:49
it happened when i started assault on avatar from kashyyyk instance frog
i will post screenshot soon

**Comment by IrishDarkshadow** [comment] 2019-12-02 11:58
Something like this?
![image](https://user-images.githubusercontent.com/12293802/69957486-b0465400-14fa-11ea-94f0-cb6c6f48002d.png)

Those show up for an object that the server is able to place into the game world but the client does not have appearance files for.  The appearance files for ship models have been in the game for a long time and so I suspect there is something wrong with your client. What client are you using? Have you updated it?

**Comment by Tekaoh** [comment] 2019-12-02 19:39
I've seen missing appearance files for random objects along ground-based quests, so I wouldn't be shocked if you found something missing in space as well. Unfortunately, I don't really space personally so I don't know. But if you come across a missing appearance, I'd suggest opening a unique issue for each broken object and providing _AS MUCH DETAIL AS POSSIBLE_ so that someone can look into fixing that particular object. Screenshots, waypoints, quest names would all be examples of essential information for a dev to track down your issue.

**Comment by Cekis** [comment] 2020-02-24 21:02
Closing... not a bug.

**Closed by Cekis** 2020-02-24 21:02 UTC

**Comment by LORDANDERSON** [comment] 2020-02-27 04:24
NATALIE PADME IS MY DARLING LOVING WIFE FOREVER!!!!!!!! SHE LOVES ME WITH
ALL HER HEART AND SOUL FOREVER!!!!!!!!! ME AND NATALIE WILL KILL ALL MY
CRAZY EVIL ENEMIES TRASH!!!!!!!!!! ME AND NATALIE PADME LOVE EACH OTHER
SINCE HER BIRTH!!!!!!! I AM SUPREME IMMORTAL MOST BEAUTIFUL INTELLIGENT GOD
HORUS HACKER PRINCE GAGARIN LORD SKYWALKER VADER AND NATALIE IS MY PROPERTY
WIFE FOREVER!!!!!!!!!! I OWN HER FOREVER!!!!!!!!!! SHE IS MINE!!!!!!! AND I
LOVE HER AND SHE LOVES ME WITH ALL HER HEART AND SOUL FOREVER!!!!!!!!!! ALL
OTHERS ARE TRASH!!!!!!!! ONLY ME AND MY DARLING LOVING WIFE NATALIE PADME
ARE SUPREME FOREVER!!!!!!!!!!! I ALWAYS FUCK AND LICK AND KISS MY SEXY
TASTY SWEET LOVING CARING MOST BEAUTIFUL WIFE NATALIE!!!!!!!! AND I WILL
KILL ALL MY ENEMIES EVERYWHERE!!!!!!!!!!!!!
https://linktr. ee/HORUSHACKER
https://web.tunecore. com/music/supremegodhorushacker

http://www.swgruminations. com

https://drive.google.com/…/19nG9PHYvUUACoUL1hUsbWBwFPd…/view

https://embed.restream.io/player/index.html…

пн, 2 дек. 2019 г. в 09:23, Cekis <notifications@github.com>:
