### ISSUE TITLE
Infamous booster bugs -   Lockout  & Uninstall Fc/Astromech

### ISSUE THREAD

**Issue by djmalsidious** [SWG-Source/dsrc#38] opened 2019-05-20 15:35 UTC
Old issues from live.  Not sure if they ever figured it out either.

Bug 1:
Take any booster.   install a flight computer/astromech.    Once fc/astro shows red for active,  uninstall booster.    will DEF unintentionally uninstall fc/astro.

Bug 2:
Booster Lockout bug.    Prevents activation of keyboard/joystick activation.  Can only be activated through chat window.   Don't know how the booster lockout triggers.  there is no error message.

**Comment by Cekis** [comment] 2020-02-28 16:08
RE: Bug 1...  I took a look at this and it's a pretty major issue.  When you uninstall a Booster, the game sends signals back and forth between the server and the scripting engine (they are two different "environments").  The problem is, that the two environments are NOT in sync.  Because of how the game operates IN GAME right now (shunts, damage, etc), I'm concerned if I fix the real issue (making things in sync again) that a LOT of the logic will be off.  Which means, I'll break other things that I didn't know I was breaking.  It may just be better to leave this one alone.  Need to consult with some other guys first though.

**Comment by Cekis** [comment] 2020-02-28 16:09
RE: Bug 2.  I really don't even know what the issue is here.  Can you describe how to make it happen?

**Comment by Cekis** [comment] 2020-03-04 05:40
Closing as bug 2 cannot be reproduced and bug 1 has a new bug report assigned to it.

**Closed by Cekis** 2020-03-04 05:40 UTC
