### ISSUE TITLE
Characters Not Getting Any Cloner Locations in the Menu Upon Death

### ISSUE THREAD

**Issue by IrishDarkshadow** [SWG-Source/dsrc#42] opened 2019-09-03 23:11 UTC
Sometimes when a character dies they get the menu for cloner locations but nothing is in the list. I was able to replicate this tonight like this:

(1) enter god mode
(2) use frog to flag all instances
(3) use frog warp to Aurillia
(4) pay shuttle pilot to take me to IG-88 instance
(5) kick mouse droid and insta-die to first damage (cl1 toon)
(6) get cloner menu but it's got no entries
(7) use /gmr to revive the toon which works properly

When that was done I noticed an error in the server console:
![image](https://user-images.githubusercontent.com/12293802/64214465-8bfdbb80-cea8-11e9-9a38-bbe83dce6fd6.png)

**Comment by lordbogit** [comment] 2019-09-16 11:13
i can confirm but bound locations work though thay say "unknown" even if your on the same planet

**Comment by AlecH92** [comment] 2019-09-16 13:21
This might have been lost in the discord, but the issue only appears on Tatooine I believe. It is missing the `planet.base_planet` script. You should be able to manually attach it:
/server getpla tatooine (returns tatooine planet oid, 140000014 usually?)
/script attach planet.planet_base `theoidhere`

**Comment by Cekis** [comment] 2019-09-19 03:54
Closed as it was caused by the 2.1 VM

**Closed by Cekis** 2019-09-19 03:54 UTC
