### ISSUE TITLE
Tansarii Station - Spawn Loop

### ISSUE THREAD

**Issue by GrandMasterVader** [SWG-Source/dsrc#161] opened 2020-11-13 13:15 UTC
In Tansarii Station when you are doing Space Missions, returning from Ord Mantell, or just log off in any place, always spawn you in the room where Han Solo and Chewbacca is.

![Tansarii - Space Terminal](https://user-images.githubusercontent.com/69476485/99075971-bf4dd700-2590-11eb-9f8f-adde9a6b48f6.png)

This is the spot
![Tansarii - Spawning with Han Solo and Chew](https://user-images.githubusercontent.com/69476485/99075998-caa10280-2590-11eb-8ceb-8bf80664077c.png)

**Comment by Cekis** [comment] 2020-11-13 15:41
Can you confirm EXACTLY all the actions that is doing this?  This is happening because the server loses your relation to the area around you and will just put you in space.  The system recognizes that, but because it doesn't have a good place to put you (i.e. space), it puts you in that room.

**Comment by lordbogit** [comment] 2020-11-14 10:37
i can conferm that the act of doing space missons couse spawning in hanger bay 2 tansari insted of bay 1, i have not tryed the relog

**Comment by Cekis** [comment] 2020-11-15 18:00
I'm noticing the same... working on trying to figure out how to prevent that double-warp.

**Comment by Cekis** [comment] 2020-11-15 19:51
Changed how it checks for getting stuck in space... there is probably more work to do here, but this should be better than before.

**Comment by Cekis** [comment] 2020-11-16 17:15
Closing as confirmed working.

**Closed by Cekis** 2020-11-16 17:15 UTC

**Comment by AconiteX** [comment] 2021-08-15 02:07
I reverted fce63a97 and 50958375 through 2a2106c as this was addressed via SWG-Source/src@6c5f6b3.

When the Buildout Area Manager was modified to add the Server Load Level feature, the `SharedBuildoutAreaManager::findBuildoutAreaAtPosition` function was inadvertently impacted. Because the `isInTutorialArea()` JNI method uses `findBuildoutAreaPosition` in `NewbieTutorial.cpp`, this broke too, just like cloning in instanced areas which was recently fixed.

I can't replicate this issue anymore, but I want to make a big caveat here that NPE is instanced so it doesn't behave like normal space/ground in terms of logging out. If your character is unloaded and the area goes inactive, you may very well login again to be teleported to Hangar 2 of Tansarii. Please let me know if problems persist.
