### ISSUE TITLE
WoD The Whole Truth (blocked cave entrance)

### ISSUE THREAD

**Issue by lordbogit** [SWG-Source/dsrc#96] opened 2020-04-12 10:01 UTC
Cave Entance blocked 
![image](https://user-images.githubusercontent.com/353448/79066078-dd76f000-7cac-11ea-8e53-89cdfb0c5afd.png)
reminds me of the bunker on tat
but unstck dus put you outside

**Comment by IrishDarkshadow** [comment] 2020-04-13 00:45
![image](https://user-images.githubusercontent.com/12293802/79083721-e1942380-7d27-11ea-9a4d-64486e7855ca.png)
![image](https://user-images.githubusercontent.com/12293802/79083770-1c965700-7d28-11ea-9e14-53428ceff59d.png)
![image](https://user-images.githubusercontent.com/12293802/79083801-4c455f00-7d28-11ea-9cbf-9fd87ff580b3.png)

You can get out by hugging the left wall and sliding by the boulder. That will do as a workaround for the moment. It doesn't seem to be like the tat bunker issue with a misaligned portal, there is an actual object here that is blocking the exit.

**Comment by AlecH92** [comment] 2020-04-13 01:04
Terrain/dathomir.trn from final day client. Update server side as well as clientside.

**Comment by IrishDarkshadow** [comment] 2020-04-13 01:12
Both server and client side are using the final day version of dathomir.trn (patch 57).
![image](https://user-images.githubusercontent.com/12293802/79084524-2de16280-7d2c-11ea-8a4e-c52dce3bf96f.png)

**Comment by AlecH92** [comment] 2020-04-13 22:11
Interesting, I was pretty sure we used the final day dath trn file. The placed caves were manually rotated to try and get existing quest-coordinates as close as possible.

**Comment by IrishDarkshadow** [comment] 2020-04-16 01:12
Progress.....there are apparently 3 boulders stuffed into that cave entrance. They are being placed there by datatables/buildout/dathomir/dathomir_5_5.iff on the CLIENT side. The file comes from patch 56 and has 30 rows in it. When I remove the 3 rows matching the boulders I can walk into and out of the cave with no problem. 

This is not the full solution though as the terrain intersects the cave entrance so from the outside it looks like the cave is sealed (it's not you can walk though) and when you turn around and look out through the cave opening the view is fine.

![](https://cdn.discordapp.com/attachments/449692955524071434/700143572363771954/unknown.png)

**Comment by IrishDarkshadow** [comment] 2020-04-16 01:48
Fixed by extracting dathomir.trn from hotfix 57. When that file is used in conjunction with the updated client side buildout for dathomir_5_5.iff the issue is resolved.


![](https://cdn.discordapp.com/attachments/449692955524071434/700159335170310184/unknown.png)

**Closed by IrishDarkshadow** 2020-04-16 01:48 UTC
