### ISSUE TITLE
Dath - default appearance boxes

### ISSUE THREAD

**Issue by Bandit42** [SWG-Source/dsrc#109] opened 2020-04-20 14:21 UTC
while on Dath, I have been seeing some default appearance boxes showing up (a base as they state). Not really a priority but something to eventually look into. Pics provided
![screenShot0032](https://user-images.githubusercontent.com/35357152/79762293-6efee700-82d7-11ea-87ad-5d4ba4283b0d.jpg)
![screenShot0033](https://user-images.githubusercontent.com/35357152/79762306-732b0480-82d7-11ea-9efb-ec48c9ac5e81.jpg)
![screenShot0035](https://user-images.githubusercontent.com/35357152/79762344-7e7e3000-82d7-11ea-8b33-00c265ed78a1.jpg)
![screenShot0036](https://user-images.githubusercontent.com/35357152/79762355-81792080-82d7-11ea-830d-6425c9c52be8.jpg)
![screenShot0037](https://user-images.githubusercontent.com/35357152/79762563-c309cb80-82d7-11ea-8c5c-f4ec9c02152d.jpg)

**Comment by AconiteGodOfSWG** [comment] 2020-04-20 17:05
Unless I'm missing something... this isn't really a bug it's just the dynamic spawner dropping lair and base spawn points. This is how GCW populates with NPCs around the planet in the middle of nowhere and how random little groups of creatures suddenly have a nest nearby. As you explore you'll note they tend to just follow you everywhere because they populate when new characters enter a zone range if they don't already exist. You can't see the spawners (default appearance boxes) when god mode is turned off. Beyond mere visual to god characters, the appearance doesn't matter but I suppose it could be changed to one of the other spawner point assets to make that more clear.

**Comment by langelusse** [comment] 2020-04-20 17:35
Missing appearance file inside client probably

**Comment by AconiteGodOfSWG** [comment] 2020-04-20 17:41
The appearance file is not missing. It does not call one. Because there is no need for there to be one. Because it is an imaginary box that appears when you walk by and is only visible to godded characters. 

The default appearance box has shown for dynamic spawning points since the original leak. This is not a bug Source created it is how SOE shipped it. Even on a final publish client there is no asset for it...but there is no need for there to be one. It clearly says what it is.

**Comment by swglockhart** [comment] 2020-05-16 15:53
Aconite is correct here, this is not a bug - closing

**Closed by swglockhart** 2020-05-16 15:53 UTC

**Comment by Tekaoh** [comment] 2020-05-16 16:34
Actually, in some cases it might be a bug. I've come across quite a few of these even with God Mode turned off. You can spot them along the legacy quest, for example. There are cases where links to client-side assets like environment scenery aren't working properly. I've already fixed a handful of them in the past, but certainly not all of them.

**Comment by Tekaoh** [comment] 2020-05-16 16:36
I mean, this particular ones appear to be creature spawners, so that's fine. They should only appear in God Mode, as mentioned, so that's fine. Just thought I'd mention that not all default appearance boxes are non-issues

**Comment by IrishDarkshadow** [comment] 2020-05-16 16:39
There were 4 default appearance boxes on the Avatar platform that needed to be fixed last week. The usual clue to a real bug with those rather than the spawner / god mode boxes is that the real issues tend to be static. Whatever object is missing an appearance file or particle effect tends to be sitting still and doesn't essentially follow the player around like the spawners do.
