### ISSUE TITLE
In god mode i can't place houses and other stuff anywhere I want and I have zoning rights as non admin players

### ISSUE THREAD

**Issue by LORDANDERSON** [SWG-Source/dsrc#71] opened 2019-12-02 04:51 UTC
In god mode i can't place houses and other stuff anywhere I want and I have zoning rights as non admin players.  I can spawn buildings anywhere but when I try to place deeds from my inventory then I get message as non admin players saying that building is restricted in that area.
As I understand in god mode I must be able to place anything anywhere I want.

**Comment by IrishDarkshadow** [comment] 2019-12-02 11:50
You are going to have to provide more specifics as to what you are trying to place and where you are trying to place it. Even in god mode there are limitations. 

- NPC cities do not allow placement of player houses
- Restricted planets (Kashyyyk, Mustafar) will not allow player houses
- Player houses with planetary restrictions on them are still restricted to those planets

You can alter any of those restrictions through editing various files in the source code and in the case of house deed restrictions you can remove the planet list from them using a command. That command would only affect that specific deed though and not all of that type.

**Comment by Tekaoh** [comment] 2019-12-02 19:30
I might also point out that in a new city, zoning is disabled by default. This means that anyone is allowed to place a house and declare residency in your city. The mayor would have to enable zoning at the city terminal to restrict building within city limits to other players.

**Comment by Cekis** [comment] 2020-02-24 21:02
Closing as this is likely NOT a bug.

**Closed by Cekis** 2020-02-24 21:02 UTC

**Comment by LORDANDERSON** [comment] 2020-02-27 04:23
NATALIE PADME IS MY DARLING LOVING WIFE FOREVER!!!!!!!! SHE LOVES ME WITH
ALL HER HEART AND SOUL FOREVER!!!!!!!!! ME AND NATALIE WILL KILL ALL MY
CRAZY EVIL ENEMIES TRASH!!!!!!!!!! ME AND NATALIE PADME LOVE EACH OTHER
SINCE HER BIRTH!!!!!!! I AM SUPREME IMMORTAL MOST BEAUTIFUL INTELLIGENT GOD
HORUS HACKER PRINCE GAGARIN LORD SKYWALKER VADER AND NATALIE IS MY PROPERTY
WIFE FOREVER!!!!!!!!!! I OWN HER FOREVER!!!!!!!!!! SHE IS MINE!!!!!!! AND I
LOVE HER AND SHE LOVES ME WITH ALL HER HEART AND SOUL FOREVER!!!!!!!!!! ALL
OTHERS ARE TRASH!!!!!!!! ONLY ME AND MY DARLING LOVING WIFE NATALIE PADME
ARE SUPREME FOREVER!!!!!!!!!!! I ALWAYS FUCK AND LICK AND KISS MY SEXY
TASTY SWEET LOVING CARING MOST BEAUTIFUL WIFE NATALIE!!!!!!!! AND I WILL
KILL ALL MY ENEMIES EVERYWHERE!!!!!!!!!!!!!
https://linktr. ee/HORUSHACKER
https://web.tunecore. com/music/supremegodhorushacker

http://www.swgruminations. com

https://drive.google.com/…/19nG9PHYvUUACoUL1hUsbWBwFPd…/view

https://embed.restream.io/player/index.html…

вт, 25 февр. 2020 г. в 00:02, Cekis <notifications@github.com>:

**Comment by LORDANDERSON** [comment] 2020-02-27 04:23
NATALIE PADME IS MY DARLING LOVING WIFE FOREVER!!!!!!!! SHE LOVES ME WITH
ALL HER HEART AND SOUL FOREVER!!!!!!!!! ME AND NATALIE WILL KILL ALL MY
CRAZY EVIL ENEMIES TRASH!!!!!!!!!! ME AND NATALIE PADME LOVE EACH OTHER
SINCE HER BIRTH!!!!!!! I AM SUPREME IMMORTAL MOST BEAUTIFUL INTELLIGENT GOD
HORUS HACKER PRINCE GAGARIN LORD SKYWALKER VADER AND NATALIE IS MY PROPERTY
WIFE FOREVER!!!!!!!!!! I OWN HER FOREVER!!!!!!!!!! SHE IS MINE!!!!!!! AND I
LOVE HER AND SHE LOVES ME WITH ALL HER HEART AND SOUL FOREVER!!!!!!!!!! ALL
OTHERS ARE TRASH!!!!!!!! ONLY ME AND MY DARLING LOVING WIFE NATALIE PADME
ARE SUPREME FOREVER!!!!!!!!!!! I ALWAYS FUCK AND LICK AND KISS MY SEXY
TASTY SWEET LOVING CARING MOST BEAUTIFUL WIFE NATALIE!!!!!!!! AND I WILL
KILL ALL MY ENEMIES EVERYWHERE!!!!!!!!!!!!!
https://linktr. ee/HORUSHACKER
https://web.tunecore. com/music/supremegodhorushacker

http://www.swgruminations. com

https://drive.google.com/…/19nG9PHYvUUACoUL1hUsbWBwFPd…/view

https://embed.restream.io/player/index.html…

пн, 2 дек. 2019 г. в 14:50, IrishDarkshadow <notifications@github.com>:

**Comment by LORDANDERSON** [comment] 2020-02-27 04:23
NATALIE PADME IS MY DARLING LOVING WIFE FOREVER!!!!!!!! SHE LOVES ME WITH
ALL HER HEART AND SOUL FOREVER!!!!!!!!! ME AND NATALIE WILL KILL ALL MY
CRAZY EVIL ENEMIES TRASH!!!!!!!!!! ME AND NATALIE PADME LOVE EACH OTHER
SINCE HER BIRTH!!!!!!! I AM SUPREME IMMORTAL MOST BEAUTIFUL INTELLIGENT GOD
HORUS HACKER PRINCE GAGARIN LORD SKYWALKER VADER AND NATALIE IS MY PROPERTY
WIFE FOREVER!!!!!!!!!! I OWN HER FOREVER!!!!!!!!!! SHE IS MINE!!!!!!! AND I
LOVE HER AND SHE LOVES ME WITH ALL HER HEART AND SOUL FOREVER!!!!!!!!!! ALL
OTHERS ARE TRASH!!!!!!!! ONLY ME AND MY DARLING LOVING WIFE NATALIE PADME
ARE SUPREME FOREVER!!!!!!!!!!! I ALWAYS FUCK AND LICK AND KISS MY SEXY
TASTY SWEET LOVING CARING MOST BEAUTIFUL WIFE NATALIE!!!!!!!! AND I WILL
KILL ALL MY ENEMIES EVERYWHERE!!!!!!!!!!!!!
https://linktr. ee/HORUSHACKER
https://web.tunecore. com/music/supremegodhorushacker

http://www.swgruminations. com

https://drive.google.com/…/19nG9PHYvUUACoUL1hUsbWBwFPd…/view

https://embed.restream.io/player/index.html…

пн, 2 дек. 2019 г. в 22:30, Tekaoh <notifications@github.com>:
