### ISSUE TITLE
Missing Texture On Vet Reward Item - Resource Supply Generator

### ISSUE THREAD

**Issue by DevilFangs** [SWG-Source/dsrc#273] opened 2021-02-21 01:32 UTC
![screenShot0015](https://user-images.githubusercontent.com/79380880/108612919-fb6faf80-73a9-11eb-8d92-7141abf28a93.jpg)

**Comment by ResurgenceDark** [comment] 2021-02-21 10:21
I recently submitted a commit that fixed this.  The issue is there is a typo in the share tpf file.

**Comment by AconiteX** [comment] 2021-02-21 15:49
Fixed via 062e814972 and now pushed to client.

**Closed by AconiteX** 2021-02-21 15:49 UTC
